### PR TITLE
Optional self in patterns, no configuration option required

### PR DESCRIPTION
**Pull request by bnorick**
Here's what I envisioned, no additional configuration option is required and both selfless and selfish patterns are supported.

### CODE REVIEW

**Comment by bnorick** [comment]
Thoughts?

**Comment by jacebrowning** [comment]
@bnorick Thanks for submitting the PR for review! At this time I'm not planning to merge it. It's more code than I'd like to maintain for what amounts to saving a a few characters.

I really appreciate the other contributions you've made to this project! :v:

**Comment by bnorick** [comment]
I guess I'll have to code golf it then 🤣

**Comment by bnorick** [comment]
It seems pretty minimal already, to be honest, and it doesn't seem to me that it would need any maintenance. If you won't accept this sort of PR because you don't think it matters, that's fine, just let me know.

But just look at `"/path/to/root/{key}/{subkey}.toml"` vs`"/path/to/root/{self.key}/{self.subkey}.toml"` :rofl:

**Comment by jacebrowning** [comment]
I don't think avoiding the need for the `self.` prefix is a big concern right now, but thanks for the proposal!

**Pull request closed without merging**
