### PR TITLE
Try to be smart in the argument filling logic

### PR DESCRIPTION
**Pull request by ramnes**
Here is an alternative implementation to the hack described at the end of #139, that also fixes that same issue... but I'm not sure why. :smile:

### CODE REVIEW

**Comment by jacebrowning** [comment]
Thanks! I am also unsure why this works over the previous implementation, but I prefer this over the existing hack. Perhaps a `yield` in a `try...except` behaves differently than I understood.

**Comment by jacebrowning** [comment]
I found another edge case where we'll need to handle parameters with default values. I'll incorporate your solution from #140 in a new PR.

**Comment by ramnes** [comment]
And thank you for checking the PR that fast! What is the said edge case?

**Comment by jacebrowning** [comment]
I added a failing test in https://github.com/jacebrowning/datafiles/pull/144 to show the edge case.

**Pull request merged**
